### ISSUE TITLE
Comparison to CNN

### ISSUE THREAD

**Issue by UrosKarajovic** [youyexie/Chess-Piece-Recognition-using-Oriented-Chamfer-Matching-with-a-Comparison-to-CNN#1]
Hi guy,
 
It's great project! But I have two questions for you:
1. Can you send me or publish code with a CNN and corresponding dataset?
2. You have taken into account the overlap of figures in terms of occlusion, but if the piece exists below the other piece, how can you separate this pieces before recognition? You will probably right recognize piece above, but piece below?

One correction:
In the 631st and 632nd line of recognition.m you haven't always divide by 4 to calculate the mean value of white and black pixels of board. If you have the pieces at this row, this number will be lower than 4!

Regards

**Comment by youyexie** [comment]
Hi,

Thanks for your interest. 

1. In the experiment, we adopted the trained CNN in https://github.com/utsavgarg/tensorflow-classification. You can find more models there and the dataset is sent to your email.

2. Since we want to analyze the occlusion individually, we assumed there is no piece right behind another piece in the experiment. If this assumption is violated, you may need a more sophicticated algorithm to determine the pieces location more precisely. With the precise location information, the oriented chamfer matching is able to recognize those two pieces with a success rate that depends on the level of occlusion.

Regarding the correction:
Thanks for pointing that out. For demo we simply estimate the intensities from the last row of the chessboard. For real applications, you can either:
1. select the empty squares based on the pieces location for estimating,
or
2. estimate the intensity from an empty chessboard and use the pre-fixed values.

Best,

**Comment by AOccLib** [comment]
Hello, 

that's a very nice project, congratulations on the results! 

As UrosKarajovic, I would be interested in the dataset. Would you mind sending it to me?

Thank you very much.

**Comment by youyexie** [comment]
> Hello,
> 
> that's a very nice project, congratulations on the results!
> 
> As UrosKarajovic, I would be interested in the dataset. Would you mind sending it to me?
> 
> Thank you very much.

Thanks! Since the images are too large, do you mind dropping me an email (youyexie@mines.edu) so I can send them to you?

**Comment by Untronix0nly** [comment]
Hello. 
It's excellent project/ I'm newbie in datascience. And want understand and reproduce your results. Can you send me a dataset and your trained cnn model, because I have weak computer to retrain model from zero(
Thank you very much. And good luck!)

**Comment by youyexie** [comment]
> Hello.
> It's excellent project/ I'm newbie in datascience. And want understand and reproduce your results. Can you send me a dataset and your trained cnn model, because I have weak computer to retrain model from zero(
> Thank you very much. And good luck!)

Sure and please provide me your email. Have fun!

**Comment by Untronix0nly** [comment]
> > Hello.
> > It's excellent project/ I'm newbie in datascience. And want understand and reproduce your results. Can you send me a dataset and your trained cnn model, because I have weak computer to retrain model from zero(
> > Thank you very much. And good luck!)
> 
> Sure and please provide me your email. Have fun!

untronix@outlook.com

**Comment by youyexie** [comment]
> > > Hello.
> > > It's excellent project/ I'm newbie in datascience. And want understand and reproduce your results. Can you send me a dataset and your trained cnn model, because I have weak computer to retrain model from zero(
> > > Thank you very much. And good luck!)
> > 
> > 
> > Sure and please provide me your email. Have fun!
> 
> [untronix@outlook.com](mailto:untronix@outlook.com)

Sent!

**Comment by gordonfreemanfree** [comment]
Hi,

I really enjoyed reading your paper. Nice work! 
As the people before, I'm interested in the dataset. Could you send them to me? Or let me know if I can drop you an email.

Best,

**Comment by youyexie** [comment]
> Hi,
> 
> I really enjoyed reading your paper. Nice work!
> As the people before, I'm interested in the dataset. Could you send them to me? Or let me know if I can drop you an email.
> 
> Best,

Thanks for your interest! 

I just upload the dataset at 'https://github.com/youyexie/Dataset-Of-Chessboards'.  Please don't hesitate to drop me an email (youyexie@mines.edu) if you have any other questions.

Have fun!
